version: "3.9"
services:
  backend:
    build: ./backend
    container_name: graphql
    depends_on:
      - db
    volumes:
      - ./backend:/graphql
      - backend-node_modules:/graphql/node_modules
    ports:
      - "4000:4000"
    environment:
      WAIT_HOSTS: db:3306
      GRAPHQL_LEARNING_GITHUB_CLIENT_ID:
      GRAPHQL_LEARNING_GITHUB_CLIENT_SECRET:
  frontend:
    build: ./frontend
    container_name: react
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - frontend-node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
  db:
    image: "mysql:8-debian"
    platform: "linux/amd64"
    container_name: mysql8
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: developmentdb
      MYSQL_USER: developmentuser
      MYSQL_PASSWORD: developmentpassword
volumes:
  backend-node_modules:
  frontend-node_modules: